import Header from "@/components/Header";
import "/css/style.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Social Dance TV",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
